### ISSUE TITLE
refreshes all the time 

### ISSUE THREAD

**Issue by onu411514c** [spring-projects/spring-flo#35] opened 2018-08-28 14:00 UTC
unable to setup as it keeps on refreshing and never reaches a stable point ....
i followed the steps to setup this application turns out it is more than just frustrating to set this up

**Comment by BoykoAlex** [comment] 2018-08-28 15:00
Did you look at the sample app? Think it shows the DSL editor and visual editor in sync and doesn't refresh all the time...
A bit more details on what is refreshing all the time or some sample code to demonstrate the problem would help

**Comment by sabbyanandan** [comment] 2018-08-29 18:32
@onu411514c: It'd be good to also know which browser and version you're on.

**Comment by onu411514c** [comment] 2018-08-30 08:04
browser version -->> Version 68.0.3440.75 (Official Build) (64-bit)
node -- >  v8.11.4

**Comment by BoykoAlex** [comment] 2018-08-30 13:53
It does that on Windows i can confirm that. It's fine on Mac with the same Chrome version. I'll investigate...

**Comment by BoykoAlex** [comment] 2018-08-30 21:12
This was introduced not long ago with Angular 6 upgrade: c130c5cc59ee348b420d34d9ad9f3575f4064d95
I have upgraded `ngx-bootstrap` being used by the sample app to 3.x because wanted not to use `rxjs-compat` package. It turned out however that something is off with `ngx-bootsrap` 3.x: https://github.com/valor-software/ngx-bootstrap/issues/4494
I worked around the problem by transpiling `ngx-bootstrap.es2015.js` file at runtime by SystemJS. It worked great everywhere up until. This is very unfortunate because I couldn't find a better solution but to rollback sample to `ngx-bootstrap` 2.x and add `rxjs-compat`. (`ngx-bootstrap` is used show modal dialogs for the sample app).

I have updated the dependendy of `lite-server` and now you should be able to see the sample in other browsers on Windows. Note, however, that FF and IE are not well supported as we were aiming to get it working primarily on Chrome.

**Comment by BoykoAlex** [comment] 2018-08-30 21:12
Fixed with 5d7f8929fba4588ad6951f824ddd44e123144a39

**Closed by BoykoAlex** 2018-08-30 21:12 UTC
Labels: question

**Comment by sabbyanandan** [comment] 2018-09-05 18:38
@onu411514c: Please try it out and let us know if you have any other feedback. Thanks for reporting this!
